# Generated by Django 5.0.6 on 2024-05-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualification', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='photo_employees/')),
                ('article_url', models.URLField(blank=True, null=True)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('article_url', models.URLField(blank=True, null=True)),
                ('page_type', models.IntegerField(blank=True, choices=[(1, 'MAIN_PAGE'), (2, 'FACULTY_HISTORY_PAGE'), (3, 'MEMBERS_PAGE'), (4, 'RESEARCH_WORK_PAGE'), (5, 'INTERNATIONAL_COOPERATION_PAGE'), (6, 'EMPLOYMENT_PAGE')], null=True)),
            ],
        ),
    ]
