# Generated by Django 5.0.6 on 2024-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0003_employees_position_alter_employees_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
